# version: "3"
# services:
#   app:
#     build: ./app
#     ports: 
#       - "8000:8000"
#     depends_on:
#       - db

#   db: 
#     image: postgres:14
#     # restart: always
#     environment: 
#       POSTGRES_USER: postgres 
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: postgres
#     ports:
#       - "5433:5433"
#     volumes: 
#       - dbdata:/var/lib/postgresql/data 
  
#   volumes: 
#     dbdata:


version: '3.8' 
services: 
  postgres: 
    image: postgres 
    environment: 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: postgres 
    ports: 
      - "5433:5432" 
    # volumes: 
    #   - dbdata:/var/lib/postgresql/data 
  web: 
    build: . 
    ports:
     - "8000:8000"
    depends_on:
     - postgres 
  # volumes: 
  #   dbdata: