version: "3.8"

services:
  db:
    image: postgres:14-alpine
    # networks:
    #   - postgres_net
    container_name: "postgres"
    restart: always
    hostname: "localhost"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    expose:
      - 5432
    stdin_open: true
    tty: true
